const bumper = (x, z, r = 1) => ({ type: "bumper", x, z, r, height: 2.8 });
const wall = (x, z, w, h = 2.5, d = 1) => ({
  type: "wall",
  x,
  z,
  y: h / 2,
  w,
  h,
  d,
});
const mill = (x, z, speed = 0.65) => ({
  type: "mill",
  x,
  z,
  y: 4,
  r: 4.5,
  width: 0.85,
  depth: 0.65,
  speed,
});
const fan = (x, z, fx, fz) => ({
  type: "fan",
  x,
  z,
  rx: 4,
  rz: 9,
  height: 7,
  fx,
  fz,
  fy: 1.8,
});
const portal = (x, z, ex, ez) => ({
  type: "portal",
  x,
  z,
  y: 2.3,
  r: 2,
  exit: { x: ex, z: ez, y: 2.3 },
});
const pad = (x, z) => ({ type: "pad", x, z, r: 2.5, kick: 9 });
const layouts = [
  [
    "Welcome to the Bounce",
    3,
    [0, 38],
    [
      [0, 0],
      [-6, 19],
      [0, 38],
    ],
    "Pink bumpers give a lively rebound. Slip through the middle or take the wide mint lane.",
    [bumper(-3, 17), bumper(3, 22), bumper(-4, 28)],
  ],
  [
    "Windmill Wishes",
    3,
    [0, 47],
    [
      [0, 0],
      [-10, 25],
      [0, 47],
    ],
    "Thread the turning sails for the short line. Both sides stay open for a patient approach.",
    [mill(0, 24), bumper(9, 31)],
  ],
  [
    "Air Mail",
    3,
    [12, 49],
    [
      [0, 0],
      [-5, 24],
      [12, 49],
    ],
    "The blue stream pushes right and downfield. Ride the fan or stay outside its painted arrows.",
    [fan(-4, 24, 5, 3), bumper(5, 36), wall(12, 28, 6, 2)],
  ],
  [
    "Pocket Universe",
    4,
    [-8, 69],
    [
      [0, 0],
      [-12, 32],
      [-8, 69],
    ],
    "Fly through the purple portal to skip ahead. It keeps your speed and direction, so plan the exit.",
    [portal(3, 19, -5, 48), wall(0, 34, 12, 3), bumper(-13, 47)],
  ],
  [
    "Pop Goes the Disc",
    3,
    [0, 48],
    [
      [0, 0],
      [-9, 24],
      [0, 48],
    ],
    "A low shot onto the yellow trampoline becomes a high shot. Go over the candy wall or around it.",
    [pad(0, 17), wall(0, 25, 11, 3.2), bumper(-8, 34), bumper(8, 34)],
  ],
  [
    "Pinball Picnic",
    4,
    [11, 64],
    [
      [0, 0],
      [-9, 23],
      [11, 45],
      [11, 64],
    ],
    "A bumper garden rewards creative banks. The outer lawn offers a calmer two-stage route.",
    [
      bumper(-3, 18, 1.4),
      bumper(5, 24, 1.4),
      bumper(-5, 32, 1.4),
      bumper(5, 40, 1.4),
      bumper(16, 46, 1.4),
      wall(-12, 38, 1, 3, 12),
    ],
  ],
  [
    "Double Trouble",
    4,
    [-8, 73],
    [
      [0, 0],
      [11, 24],
      [-13, 51],
      [-8, 73],
    ],
    "Two windmills turn in opposite directions. Shape an S-line between them or loop around the sails.",
    [
      mill(-2, 24, 0.65),
      mill(3, 47, -0.85),
      fan(13, 33, -4, 2),
      bumper(-13, 58),
    ],
  ],
  [
    "The Long Way Round",
    4,
    [0, 87],
    [
      [0, 0],
      [-14, 26],
      [-14, 53],
      [0, 87],
    ],
    "A portal is the bold shortcut; the outside lane is always available. Watch the exit bumper!",
    [
      portal(5, 23, -7, 62),
      wall(0, 34, 15, 4),
      wall(7, 51, 12, 3),
      bumper(-3, 70, 1.5),
      pad(-14, 43),
    ],
  ],
  [
    "Big Top Finale",
    5,
    [0, 98],
    [
      [0, 0],
      [-12, 26],
      [12, 53],
      [-10, 77],
      [0, 98],
    ],
    "One last carnival ride: sails, a tailwind and a portal shortcut. Pick your line and send it.",
    [
      mill(0, 23),
      fan(-12, 39, 3, 5),
      bumper(2, 47, 1.6),
      portal(10, 52, -8, 80),
      wall(0, 65, 11, 3),
      pad(-11, 67),
      bumper(5, 88),
    ],
  ],
];
export const playgroundHoles = layouts.map(
  ([name, par, pin, route, hint, gadgets], i) => ({
    id: i + 1,
    name,
    par,
    pin: { x: pin[0], z: pin[1] },
    route,
    hint,
    gadgets,
    theme: "playground",
    length: Math.round(Math.hypot(...pin)),
    trees: [],
    rocks: [],
    water: [],
  }),
);
export const playground = {
  id: "cloud-carnival-v1",
  name: "Cloud Carnival",
  mode: "Playground",
  par: 33,
  holes: playgroundHoles,
};
